# NUMPY X PANDAS

NumPy y Pandas son dos bibliotecas fundamentales en Python para el análisis de datos y la manipulación de estructuras de datos:

NumPy es una biblioteca de Python para el cálculo numérico que proporciona soporte para arrays multidimensionales y funciones matemáticas de alto rendimiento.

Pandas es una biblioteca de Python que ofrece estructuras de datos y herramientas para la manipulación y análisis de datos. A diferencia de NumPy, que está orientado a operaciones numéricas en arrays, Pandas está diseñado para trabajar con datos estructurados y etiquetados, como hojas de cálculo y bases de datos.

Los objetivos de este JN son:

1. Definir arrays unidimensionales y multidimensionales.
2. Aprovechar los métodos y funciones incorporados en NumPy.
3. Realizar operaciones matemáticas con NumPy.
4. Realizar el corte y la indexación de arrays.

In [12]:
# Importar las librerías
import numpy as np
import pandas as pd

1: Familiarizarse con la creación de arreglos unidimensionales y multidimensionales en NumPy.

Un array (o arreglo) es una estructura de datos que almacena una colección de elementos. En el contexto de la biblioteca NumPy, que es ampliamente utilizada para operaciones numéricas y de análisis de datos, los arrays son especialmente útiles para trabajar con datos numéricos y realizar operaciones matemáticas.

In [13]:
# Crear un array unidimensional
array_unidimensional = np.array([50, 100, 150, 200])
array_unidimensional

array([ 50, 100, 150, 200])

In [14]:
# Crear un array unidimensional a partir de una tupla
l = (50, 100, 150, 200)
array_unidimensional = np.array(l)

array_unidimensional

array([ 50, 100, 150, 200])

In [15]:
# Crear un array bidimensional (matriz)
array_multidimensional = np.array ([[50, 100, 150],
                               [200, 250, 300]])
array_multidimensional

array([[ 50, 100, 150],
       [200, 250, 300]])

array Unidimensional: Usamos np.array() para crear un vector simple.
array Bidimensional: Usamos una lista de listas dentro de np.array() para definir una matriz.

2: Utilizar funciones y métodos de NumPy para generar arreglos aleatorios y especiales.

In [16]:
# Crear un arrray unidimensional con números aleatorios entre 0 y 1
array_unidimensional = np.random.rand(5)
array_unidimensional

array([0.04854287, 0.87026286, 0.42439282, 0.08637492, 0.23134846])

In [17]:
# Crear un arrray bidimensional con números aleatorios entre 0 y 1
array_bidimensional = np.random.rand(3, 4)
array_bidimensional

array([[0.82058651, 0.87975796, 0.14682672, 0.80680023],
       [0.87449008, 0.8233965 , 0.90413538, 0.42209961],
       [0.48051922, 0.79283336, 0.33340672, 0.93267334]])

In [18]:
# Generar un número entero aleatorio entre 0 y 10
numero_aleatorio = np.random.randint(0, 10)
numero_aleatorio

8

In [19]:
# Crear un arrray unidimensional con números enteros aleatorios entre 1 y 100
array_unidimensional = np.random.randint(1, 100, size=5)
array_unidimensional

array([19,  1, 84, 11, 56])

In [20]:
# Crear un arrray bidimensional con números enteros aleatorios entre 10 y 50
array_bidimensional = np.random.randint(10, 50, size=(3, 4))
array_bidimensional

array([[29, 17, 11, 22],
       [40, 45, 27, 14],
       [15, 34, 22, 26]])

In [21]:
# Crear un arrray con valores secuenciales de 0 a 9
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Crear un arrray con valores secuenciales del 5 al 15 (sin incluir 15) con paso de 2
array = np.arange(5, 15, 2)
array

array([ 5,  7,  9, 11, 13])

In [23]:
# Crear un arrray con valores secuenciales desde 0.5 hasta 5.0 con paso de 0.5
array = np.arange(0.5, 5.0, 0.5)
array

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Una matriz es una estructura matemática que se utiliza para representar datos en un formato tabular, consistente en un conjunto de números organizados en filas y columnas.

In [24]:
# Crear una matriz diagonal de unos
matriz_diagonal = np.eye(3, dtype=int)
matriz_diagonal

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
# Crear una matriz diagonal de unos con dimensiones 4x5
matriz_diagonal = np.eye(4, 5, dtype=int)
matriz_diagonal

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [26]:
# Crear una matriz diagonal superior (diagonal con desplazamiento k=1)
matriz_diagonal_superior = np.eye(4, k=1, dtype=int)
matriz_diagonal_superior

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [27]:
# Crear una matriz de unos de 3x3
matriz_de_unos = np.ones((3, 3), dtype=int)
matriz_de_unos

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
# Crear una matriz de ceros de 3x3
matriz_de_ceros = np.zeros((3, 3), dtype=int)
matriz_de_ceros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

np.random.rand() y np.random.randint(): Generan arreglos con valores aleatorios.
np.arange(): Crea arreglos con valores secuenciales.
Matrices Especiales: np.eye() crea matrices diagonales, np.ones() y np.zeros() crean matrices llenas de unos y ceros, respectivamente.

3: Aplicar operaciones matemáticas básicas y utilizar funciones NumPy para cálculos.

In [29]:
# Operaciones elementales con arrays
# Dividir dos arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

resultado = array1 / array2

print("Resultado de la suma:")
resultado

Resultado de la suma:


array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [30]:
# Sumar dos arrays usando np.add()
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

resultado = np.add(array1, array2)

print("Resultado de la suma usando np.add():")
resultado

Resultado de la suma usando np.add():


array([[ 8, 10, 12],
       [14, 16, 18]])

In [31]:
# Calcular la distancia euclidiana entre dos puntos (x1, y1) y (x2, y2)
x1, y1 = 2, 3
x2, y2 = 5, 7

distancia = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)

print("La distancia entre los puntos es:", distancia)

La distancia entre los puntos es: 5.0


In [32]:
# Operaciones con escalar
# Sumar un escalar a cada elemento del array
array = np.array([1, 2, 3, 4, 5])
result = array + 10

print("Array original:", array)
print("Array después de sumar el escalar:", result)

Array original: [1 2 3 4 5]
Array después de sumar el escalar: [11 12 13 14 15]


In [47]:
# Operaciones entre matrices y vectores
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
vector = np.array([1, 2, 3])

# Restar el vector de cada fila de la matriz
result = matrix - vector

print("Matriz original:")
print(matrix)
print("Vector:")
print(vector)
print("Matriz después de restar el vector:")
result

Matriz original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Vector:
[1 2 3]
Matriz después de restar el vector:


array([[ 9, 18, 27],
       [39, 48, 57],
       [69, 78, 87]])

In [34]:
# Sumar el array unidimensional a cada fila del array bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d

print("Array 2D original:")
print(array_2d)
print("Array 1D:")
print(array_1d)
print("Array 2D después de sumar el array 1D:")
result

Array 2D original:
[[1 2 3]
 [4 5 6]]
Array 1D:
[10 20 30]
Array 2D después de sumar el array 1D:


array([[11, 22, 33],
       [14, 25, 36]])

4: Practicar cómo acceder y modificar datos en arreglos usando indexación y corte.

La indexación es el proceso de acceder a elementos específicos dentro de una estructura de datos utilizando índices. En programación y análisis de datos, la indexación se aplica a diversos tipos de datos, como listas, arrays, matrices, y DataFrames, permitiendo obtener o modificar elementos en posiciones específicas.

In [35]:
# Indexar array unidimensional
array_1d = np.array([10, 20, 30, 40, 50])
# Acceder al elemento en el índice 2
element = array_1d[2]

print("Elemento en el índice 2:", element)

Elemento en el índice 2: 30


In [36]:
# Indexar en arrays bidimensional
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Acceder al elemento en la fila 1, columna 2
element = array_2d[1, 2]

print("Elemento en la fila 1, columna 2:", element)

Elemento en la fila 1, columna 2: 6


In [37]:
# Indexar en array tridimensional
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Acceder al elemento en la capa 1, fila 0, columna 2
element = array_3d[1, 0, 2]

print("Elemento en la capa 1, fila 0, columna 2:", element)

Elemento en la capa 1, fila 0, columna 2: 9


In [50]:
# Indexar en una matriz bidimensional
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Acceder al elemento en la fila 1, columna 2
element = matrix[1, 2]

print("Matriz original:")
print(matrix)
print("Elemento en la fila 1, columna 2:")
element


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en la fila 1, columna 2:


6

In [49]:
# Cortar (slicing) en arreglos unidimensionales
# Obtener un subconjunto del array (desde el inicio hasta el penúltimo elemento)
array = np.array([10, 20, 30, 40, 50])
subset = array[:-1]

print("Array original:", array)
print("Subset (desde el índice 0 hasta el penúltimo elemento):", subset)

Array original: [10 20 30 40 50]
Subset (desde el índice 0 hasta el penúltimo elemento): [10 20 30 40]


In [51]:
# Obtener un subconjunto del array (todas las filas y todas las columnas excepto la última)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subset_2d = array_2d[:, :-1]

print("Array 2D original:")
print(array_2d)
print("Subset 2D (todas las filas y todas las columnas excepto la última):")
subset_2d

Array 2D original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Subset 2D (todas las filas y todas las columnas excepto la última):


array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
# Seleccionar filas específicas en una matriz (FIla 1)
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
row = matrix[1]

print("Matriz original:")
print(matrix)
print("Fila obtenida (fila 1):")
row

Matriz original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Fila obtenida (fila 1):


array([40, 50, 60])

In [42]:
# Seleccionar múltiples filas en una matriz (Filas 0 y 2)
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
rows = matrix[[0, 2]]

print("Filas obtenidas (fila 0 y fila 2):")
rows

Filas obtenidas (fila 0 y fila 2):


array([[10, 20, 30],
       [70, 80, 90]])

In [43]:
# Seleccionar elementos impares en una matriz
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

odd_elements = matrix[matrix % 2 != 0]

print("Elementos impares:")
odd_elements

Elementos impares:


array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [44]:
# Seleccionar la última fila en una matriz (Reemplazar la última fila con ceros)
X = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
X[-1, :] = 0

print("Matriz después de reemplazar la última fila con ceros:")
X

Matriz después de reemplazar la última fila con ceros:


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [46]:
# Seleccionar la última columna en una matriz (Reemplazar la última columna con ceros)
X = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
X[:, -1] = 0

print("Matriz después de reemplazar la última columna con ceros:")
X

Matriz después de reemplazar la última columna con ceros:


array([[ 2, 30, 20, -2,  0],
       [ 3,  4, 40, -3,  0],
       [-3,  4, -6, 90,  0],
       [25, 45, 34, 22,  0],
       [13, 24, 22, 32,  0]])